# Site settings
title: Data Scientists against poverty
description: A place where data scientists cooperate to end the poverty 
cover: assets/images/radhakrishna.jpg
logo: assets/images/logo.png
favicon: assets/images/favicon.png
baseurl: https://dataubc.github.io/msalama2.github.io/. # the subpath of your site, e.g. /blog/ or / for root
url: "https://dataubc.github.io/msalama2.github.io/." # the base hostname & protocol for your site

pagination:

  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: falsehttps://dataubc.github.io/msalama2/

  per_page: 5

# Social
facebook: facebook
twitter: twitter
github:  github

#Additional Pages
about: about
contact: contact
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate-v2


# Settings for rake task
safe: False
lsi: False
username: msalama #github username
repo: msalama2 #github repository
branch: master #branch
relative_source: ../msalama/ #source directory
destination: ../hanuman-pages/ #destination directory
production_url:  https://samanyougarg.com/
source_url:  https://dataubc.github.io/msalama2.github.io/.  #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
